name = "ReadHTML"
uuid = "fd62e8aa-001b-5ebf-84b5-335f2920b78b"
authors = ["goropikari <goropikari56@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
